-- V10__create_notification_broadcasts — append-only admin broadcast log (TM-359 / epic TM-358)
--
-- "Who sent what to how many, when, with what aggregate outcome." Every admin broadcast appends
-- exactly one immutable header row here when the send endpoint (a later ticket) runs. This is the
-- durable, queryable history of admin messages to real users. It is deliberately NOT audit_events
-- (that table is single-target: one action against one target); a broadcast fans out to many
-- recipients, so it gets its own header table here PLUS one summary BROADCAST_SENT row in
-- audit_events (the same dual pattern device_tokens uses).
--
-- Append-only BY DESIGN, mirroring audit_events (V4): the NotificationBroadcast entity exposes no
-- mutators, NotificationBroadcastRepository declares no update/delete, and created_at is
-- DB-authoritative (default now()) so the clock can't be caller-supplied. Flyway owns this DDL;
-- Hibernate runs validate-only, so the entity must match it exactly.
--
-- The child per-recipient table (notification_broadcast_recipients) is deliberately DEFERRED to a
-- follow-up; v1 stores aggregate counters + a skipped count on this header only.
--
--   actor_uid        Firebase UID of the admin who sent the broadcast (required — always attributed).
--   title            Notification title as sent.
--   body             Notification body as sent.
--   route            Optional in-app deep-link/route the notification opens; NULL if none.
--   recipient_count  How many recipients the broadcast resolved to at send time.
--   targeted         Devices/recipients targeting was attempted against.
--   delivered        Successfully delivered.
--   pruned           Tokens pruned because FCM reported them unregistered/invalid.
--   failed           Delivery attempts that failed (non-prune errors).
--   skipped          Recipients skipped (e.g. opted out / no device token).
--   created_at       DB-authoritative timestamp (now()).
CREATE TABLE notification_broadcasts (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_uid       VARCHAR(128)  NOT NULL,
    title           VARCHAR(255)  NOT NULL,
    body            VARCHAR(2000) NOT NULL,
    route           VARCHAR(255),
    recipient_count INTEGER       NOT NULL,
    targeted        INTEGER       NOT NULL DEFAULT 0,
    delivered       INTEGER       NOT NULL DEFAULT 0,
    pruned          INTEGER       NOT NULL DEFAULT 0,
    failed          INTEGER       NOT NULL DEFAULT 0,
    skipped         INTEGER       NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now()
);

-- Broadcasts are read by actor ("what did this admin send") and most-recent-first.
CREATE INDEX idx_notification_broadcasts_actor      ON notification_broadcasts (actor_uid);
CREATE INDEX idx_notification_broadcasts_created_at ON notification_broadcasts (created_at DESC);
