-- V11__create_events — events + attendance persistence (TM-391 / events epic)
--
-- The durable home for meetup events and who is going to them. Two tables: `events` (one row per
-- event, soft-deleted per the house pattern from V3) and `event_attendance` (one row per
-- user-per-event, hard-deleted on leave — the UNIQUE pair makes a rejoin a clean re-insert).
-- Flyway owns this DDL; Hibernate runs validate-only, so the Event/EventAttendance entities must
-- match it exactly.
--
-- Time model: all instants (start/end/visibility window) are stored as TIMESTAMPTZ — i.e. UTC on
-- the wire and in the column — plus the event's IANA timezone id (e.g. "Europe/London") as text.
-- The backend never renders local times; clients combine instant + timezone to display, which
-- keeps DST correct without any server-side conversion.
--
--   heading           Short display title.
--   description       Full body text.
--   location_text     Free-text venue ("Marhaba Cafe, 12 High St"). Always present, even for
--                     online events ("Online").
--   map_url           Optional link to a map pin; NULL when there is none.
--   online_url        Optional join link for online/hybrid events; NULL for in-person only.
--   timezone          IANA timezone id of the event's locale; pairs with the instants above.
--   start_at          When the event starts (UTC instant).
--   end_at            Optional end instant; NULL = open-ended.
--   visibility_start  From when the event appears in listings.
--   visibility_end    Until when it appears. Both NOT NULL: every event has an explicit window.
--   capacity          Max GOING attendees; NULL = unlimited (no waitlisting ever kicks in).
--   image_path        Optional storage path of the event image; NULL = themed placeholder.
--   status            PUBLISHED | CANCELLED, stored as VARCHAR via Hibernate EnumType.STRING
--                     (same convention as users.role). A cancelled event stays readable — it is
--                     hidden from the visible-now listing but keeps its history.
--   created_by        FK to users(id) — the admin who created the event. People are always
--                     resolved through the User aggregate (which hides soft-deleted accounts);
--                     no ON DELETE action needed because accounts are only ever soft-deleted.
--   created_at/updated_at  created_at is DB-authoritative (now()); updated_at is bumped by the
--                     app on mutation (same convention as device_tokens).
--   deleted_at/version  House soft-delete + optimistic-lock pair (V3): NULL deleted_at = active,
--                     @Version rejects concurrent stale writes with a 409.
CREATE TABLE events (
    id               BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    heading          VARCHAR(255)  NOT NULL,
    description      VARCHAR(4000) NOT NULL,
    location_text    VARCHAR(500)  NOT NULL,
    map_url          VARCHAR(2048),
    online_url       VARCHAR(2048),
    timezone         VARCHAR(64)   NOT NULL,
    start_at         TIMESTAMPTZ   NOT NULL,
    end_at           TIMESTAMPTZ,
    visibility_start TIMESTAMPTZ   NOT NULL,
    visibility_end   TIMESTAMPTZ   NOT NULL,
    capacity         INTEGER,
    image_path       VARCHAR(512),
    status           VARCHAR(16)   NOT NULL DEFAULT 'PUBLISHED',
    created_by       BIGINT        NOT NULL REFERENCES users (id),
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    deleted_at       TIMESTAMPTZ,
    version          BIGINT        NOT NULL DEFAULT 0
);

-- The visible-now listing filters on the visibility window (+ status) and orders by start time.
CREATE INDEX idx_events_visibility ON events (visibility_start, visibility_end);
CREATE INDEX idx_events_start_at   ON events (start_at);
CREATE INDEX idx_events_created_by ON events (created_by);

-- One row per user per event. `state` is GOING or WAITLISTED (VARCHAR via EnumType.STRING);
-- capacity overflow waitlists in strict FIFO order of created_at (DB-authoritative now(), so a
-- caller can never claim an earlier queue position). Leaving an event deletes the row — the
-- UNIQUE (event_id, user_id) pair then lets a rejoin insert cleanly, at the back of the queue.
--
--   event_id   FK to events(id), ON DELETE CASCADE: attendance of a hard-removed event goes too.
--   user_id    FK to users(id), ON DELETE CASCADE. Accounts are only ever soft-deleted in-app, so
--              rows survive an account tombstone; readers must resolve people through the User
--              aggregate (whose @SQLRestriction hides tombstoned accounts) — never this table.
CREATE TABLE event_attendance (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id   BIGINT      NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    user_id    BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    state      VARCHAR(16) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_event_attendance_event_user UNIQUE (event_id, user_id)
);

-- Counts-by-state and the FIFO waitlist scan are both (event_id, state) lookups ordered by
-- created_at; the UNIQUE pair above already covers plain event_id lookups.
CREATE INDEX idx_event_attendance_event_state ON event_attendance (event_id, state, created_at);
-- "My events" reads by user.
CREATE INDEX idx_event_attendance_user_id     ON event_attendance (user_id);
