-- V14__create_event_reminder_sends — per-(event, milestone) reminder send markers (TM-394)
--
-- The idempotency ledger for the event reminder scheduler: one row per (event, milestone) that has
-- been CLAIMED for sending. The UNIQUE pair is the whole design — it is the cluster-wide "at most
-- once" guard. Unlike the broadcast cooldown (a process-local ConcurrentHashMap, fine for one
-- instance and documented as such in BroadcastService), reminders MUST NOT duplicate across
-- restarts or multiple Cloud Run instances, so the marker lives here in Postgres: every instance
-- races to INSERT first, exactly one wins, and the losers see a unique violation and skip.
--
-- Claim-then-send (at-most-once): the row is inserted-and-committed BEFORE the push fan-out, so a
-- crash between claim and send loses that one reminder rather than ever double-sending. The
-- fan-out counts are back-filled onto the row after the send (best effort), so a row left with all
-- zeros is the trace of a claimed-but-interrupted send.
--
--   event_id   FK to events(id), ON DELETE CASCADE (same convention as event_attendance): markers
--              of a hard-removed event go too. Soft-deleting/cancelling an event simply stops new
--              markers; existing ones remain as history.
--   milestone  Which reminder this row pins: T_MINUS_24H | T_MINUS_1H, stored as VARCHAR via
--              Hibernate EnumType.STRING (same convention as events.status).
--   sent_at    DB-authoritative claim instant (now()), same convention as created_at elsewhere.
--   targeted/delivered/pruned/failed  The PushFanout counts back-filled after the send — the
--              observability trail ("did the 1h reminder for event 42 actually reach anyone?").
CREATE TABLE event_reminder_sends (
    id        BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id  BIGINT      NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    milestone VARCHAR(16) NOT NULL,
    sent_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    targeted  INTEGER     NOT NULL DEFAULT 0,
    delivered INTEGER     NOT NULL DEFAULT 0,
    pruned    INTEGER     NOT NULL DEFAULT 0,
    failed    INTEGER     NOT NULL DEFAULT 0,

    -- The at-most-once guard: only one claim can ever exist per (event, milestone). The scanner's
    -- lookups are all by event_id, which this composite index already covers as its prefix.
    CONSTRAINT uq_event_reminder_sends_event_milestone UNIQUE (event_id, milestone)
);
