-- V21__create_notifications — per-user notification store (TM-452 / sprint 572, group-notifications)
--
-- The durable inbox behind the bell + panel: one row per notification delivered to one user, so
-- admin + system notifications SURVIVE beyond a transient push (the TM-374 gap where a push that
-- landed while the app was closed left no trace). This is the foundation the feed API and the
-- writers (admin-send TM-441/TM-453, event lifecycle/reminder/RSVP) all append to. Flyway owns this
-- DDL; Hibernate runs validate-only, so the Notification entity must match this table exactly.
--
--   user_id     FK to users(id), ON DELETE CASCADE (same convention as device_tokens): a
--               hard-removed account has no inbox to keep. A soft-delete (deleted_at) is a
--               tombstone — the FK never fires, so rows remain but the person no longer resolves
--               through the User aggregate (people are resolved through UserRepository, never here).
--   type        ADMIN_MESSAGE | EVENT_UPDATED | EVENT_CANCELLED | WAITLIST_OFFER | RSVP_CONFIRMED |
--               EVENT_REMINDER. Stored as VARCHAR via Hibernate EnumType.STRING (same convention as
--               users.role / device_tokens.platform) so values can be added without a DB type
--               change; existing names must never be renamed/removed (old rows reference them).
--   title/body  The notification text as delivered.
--   deep_link   Optional in-app route the notification opens (e.g. /events/42); NULL if none.
--   source_ref  Optional opaque reference to the thing that spawned it (event id / message id) so a
--               writer can de-dupe or a reader can cross-link; NULL for free-standing notifications.
--   sticky      Pinned/exempt-from-purge flag. DEFAULT false; only the admin-send path (TM-441 /
--               TM-453) may set it true — enforced there, not by the DB. The retention purge keeps
--               the last 50 NON-sticky per user and ALL sticky ones (see NotificationRepository).
--   created_at  DB-authoritative timestamp (now()), read back after insert — the newest-first order.
--   seen_at     When the user last saw it in the panel (drives the unseen bell badge); NULL = unseen.
--   read_at     When the user opened/read it (drives the unread count); NULL = unread.
CREATE TABLE notification (
    id         BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT        NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    type       VARCHAR(32)   NOT NULL,
    title      VARCHAR(255)  NOT NULL,
    body       VARCHAR(2000) NOT NULL,
    deep_link  VARCHAR(255),
    source_ref VARCHAR(128),
    sticky     BOOLEAN       NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ   NOT NULL DEFAULT now(),
    seen_at    TIMESTAMPTZ,
    read_at    TIMESTAMPTZ
);

-- The dominant read is a user's feed, newest-first (created_at DESC, id DESC as the deterministic
-- same-instant tiebreak) — this index serves both that ordering and the retention purge's
-- keep-last-50 window scan.
CREATE INDEX idx_notification_user_created_at ON notification (user_id, created_at DESC);

-- The unseen-bell-badge count is `where user_id = ? and seen_at is null`; this index also serves the
-- unread count via its user_id prefix.
CREATE INDEX idx_notification_user_seen_at ON notification (user_id, seen_at);
