-- V23__create_admin_messages — append-only admin-message campaign log (TM-441 / epic TM-432)
--
-- "Which admin sent what title/body to which resolved audience, how many recipients, when." Every
-- admin send (POST /api/v1/admin/messages) appends exactly one immutable header row here — the
-- per-campaign record the sent-history API (TM-442) reads back and that the durable per-recipient
-- notifications cross-link to (each notification carries source_ref = 'admin_message:<id>').
--
-- Deliberately NOT audit_events and NOT notification_broadcasts:
--   * audit_events is single-target (one action, one target); an admin send fans out to a whole
--     resolved audience, so — like notification_broadcasts (V10) — it gets its own header table PLUS
--     one summary ADMIN_MESSAGE_SENT row in audit_events (the same dual pattern device_tokens uses).
--   * notification_broadcasts (V10) is the *explicit-id* admin push blast (TM-359); this table is the
--     *audience-resolved* admin-messaging campaign (targeted by user / city / event, TM-440) whose
--     delivery is a durable inbox notification per recipient, not just a transient push. They are
--     distinct features with distinct history, so they get distinct tables.
--
-- Append-only BY DESIGN, mirroring audit_events (V4) and notification_broadcasts (V10): the
-- AdminMessage entity exposes no mutators, AdminMessageRepository declares no update/delete, and
-- created_at is DB-authoritative (default now()) so the clock can't be caller-supplied. Flyway owns
-- this DDL; Hibernate runs validate-only, so the entity must match it exactly.
--
--   actor_uid        Firebase UID of the admin who sent it (required — always attributed).
--   title            Message title as sent.
--   body             Message body as sent (up to ~5000 chars — the admin-message cap, TM-441; wider
--                    than the notification_broadcasts push body because an in-app message is not
--                    bounded by an FCM push payload).
--   deep_link        Optional in-app route the message opens; NULL if none. Validated against the
--                    PushRoutes admin allow-list before insert.
--   target_type      Which single audience dimension this send targeted: USER | CITY | EVENT. One
--                    target type per send is a product rule enforced at the API edge (not combined).
--   target_ref       Human-readable descriptor of the target (the id CSV, or the city name(s)) so the
--                    sent-history view can show WHO a campaign went to without re-resolving. The exact
--                    recipient membership is recoverable from the per-recipient notifications keyed by
--                    source_ref = 'admin_message:<id>'.
--   recipient_count  How many recipients the audience resolved to at send time (the A1 snapshot).
--   created_at       DB-authoritative timestamp (now()).
CREATE TABLE admin_message (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_uid       VARCHAR(128)  NOT NULL,
    title           VARCHAR(255)  NOT NULL,
    body            VARCHAR(5000) NOT NULL,
    deep_link       VARCHAR(255),
    target_type     VARCHAR(16)   NOT NULL,
    target_ref      VARCHAR(1024) NOT NULL,
    recipient_count INTEGER       NOT NULL,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now()
);

-- Sent-history (TM-442) reads by actor ("what did this admin send") and most-recent-first.
CREATE INDEX idx_admin_message_actor      ON admin_message (actor_uid);
CREATE INDEX idx_admin_message_created_at ON admin_message (created_at DESC);

-- Widen the durable notification body to hold a full admin message. The notification store (V21) was
-- sized VARCHAR(2000) for system/event notifications; an admin message may be up to ~5000 chars
-- (TM-441) and its durable inbox row must carry the WHOLE body (the transient push is a truncated
-- preview, but the in-app inbox / chat render shows the full text). Widening a VARCHAR is a
-- backward-compatible, forward-only change: every existing row still fits, and the Notification entity
-- pins no length, so validate-only Hibernate is unaffected.
ALTER TABLE notification ALTER COLUMN body TYPE VARCHAR(5000);
