-- V24__create_alerts — site-wide alert/announcement store (TM-243 / sprint 606, Quick Wins 2)
--
-- The data behind a global, scheduled, colour-coded, dismissible banner that operators can send or
-- pull WITHOUT a redeploy. The web app shell renders the active set once for every surface (the web
-- app + the Android WebView, which loads the same hosted build). Flyway owns this DDL; Hibernate runs
-- validate-only, so the Alert entity must match this table exactly.
--
-- Version note: V24 is PRE-ASSIGNED for this ticket (V23 is reserved for another wave's migration) to
-- avoid a clash across the parallel sprint; forward-only, never renumbered.
--
--   message    The notice text AS DELIVERED. This is a PUBLIC broadcast — the active read is
--              allow-listed for unauthenticated callers so a warning can show pre-login — so it must
--              never carry sensitive data. Kept short for the MVP.
--   level      INFO | WARNING | CRITICAL. Stored as VARCHAR via Hibernate EnumType.STRING (same
--              convention as users.role / notification.type) so values can be added without a DB type
--              change; existing names must never be renamed/removed (old rows reference them). Drives
--              the banner colour on the web (mapped to a Paper theme token, not a stored hue).
--   dismissal  ACKNOWLEDGE | DISMISS | PERSISTENT. The instruction the web reads to decide which
--              dismiss control to render + where it remembers the dismissal (localStorage keyed by
--              id + content-hash / sessionStorage / none). The backend never records dismissals.
--   scope      Where the alert shows. MVP only writes/honours 'global'; the column exists so
--              per-route/surface targeting is a later ADDITIVE change (no schema move needed).
--   starts_at  When the banner becomes visible (DEFAULT now() = show immediately).
--   expires_at When the banner auto-hides. The one mutable field: expire-now brings it forward to
--              now() to pull a live banner early. The active window is HALF-OPEN
--              (starts_at <= now < expires_at), matching the derived-status boundary exactly.
--   created_at DB-authoritative timestamp (now()), read back after insert — the history's newest-first
--              order. Rows are NEVER hard-deleted, so this table IS the "what was sent and when" record.
--   created_by The actor uid, from the verified admin token — attribution for the history. NOT exposed
--              on the public read; only the admin history reveals it.
CREATE TABLE alert (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message    VARCHAR(500) NOT NULL,
    level      VARCHAR(16)  NOT NULL,
    dismissal  VARCHAR(16)  NOT NULL,
    scope      VARCHAR(64)  NOT NULL DEFAULT 'global',
    starts_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ  NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by VARCHAR(128) NOT NULL
);

-- The banner's hot read is "active alerts for a scope now" (scope = ? AND starts_at <= now AND
-- expires_at > now). This composite serves the scope-equality + window range scan for that read.
CREATE INDEX idx_alert_active ON alert (scope, starts_at, expires_at);

-- The admin history is the whole table, newest-first (created_at DESC, id DESC as the deterministic
-- same-instant tiebreak) — this index serves that ordering.
CREATE INDEX idx_alert_created_at ON alert (created_at DESC);
