-- V27__conversation_message_model — the shared conversation + message store (TM-435 / group-foundation)
--
-- The single durable structure that BOTH admin broadcasts (epic TM-432) and event group chat
-- (epic TM-433) persist into, so the app's one "chat" section reads every thread — an admin
-- "from TeamMarhaba" broadcast and a per-event group conversation — out of the same three tables.
-- This migration is the wave-0 ROOT of the chat foundation: it lays down the data model only; the
-- read API (TM-436) and the push fan-out (TM-437) build on top and add no schema of their own.
--
-- Flyway owns this DDL; Hibernate runs validate-only, so the Conversation / ConversationMember /
-- Message entities must match these tables exactly (column names, nullability, enum-as-VARCHAR).
-- Conventions reused from the existing schema: BIGINT identity PKs, enums stored as VARCHAR via
-- Hibernate EnumType.STRING (as users.role / events.status), TIMESTAMPTZ instants with a
-- DB-authoritative `created_at DEFAULT now()`, and people held as plain FK ids to users(id).

-- ── conversation ────────────────────────────────────────────────────────────────────────────────
-- One row per thread. A thread is either a per-event group chat or an admin broadcast campaign.
--
--   type       EVENT_GROUP | ADMIN_BROADCAST, VARCHAR via EnumType.STRING. Discriminates the two
--              kinds that share this store; values may be added but existing names must never be
--              renamed/removed (old rows reference them).
--   event_id   FK to events(id) for an EVENT_GROUP thread; NULL for an ADMIN_BROADCAST (which is
--              not tied to any event). ON DELETE CASCADE mirrors event_attendance / the reminder
--              ledger — a hard-removed event takes its group thread with it; events are only ever
--              soft-deleted in-app, so in practice the FK never fires and the thread survives.
--   created_at DB-authoritative (now()), read back after insert — the thread-list ordering key.
--   closed_at  When the thread was closed (e.g. the event ended, or a broadcast campaign was
--              recalled); NULL = open. Soft-close, so history stays readable — never a hard delete.
CREATE TABLE conversation (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type       VARCHAR(32) NOT NULL,
    event_id   BIGINT      REFERENCES events (id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    closed_at  TIMESTAMPTZ
);

-- At most ONE conversation per event: an EVENT_GROUP thread is the event's single group chat, so
-- the fan-out (TM-437) and read API (TM-436) look it up by event_id and expect Optional (0 or 1).
-- A partial UNIQUE index enforces that without constraining the many ADMIN_BROADCAST rows whose
-- event_id is NULL (NULLs are exempt), and doubles as the index that serves the event->thread read.
CREATE UNIQUE INDEX uq_conversation_event_id ON conversation (event_id) WHERE event_id IS NOT NULL;

-- ── conversation_member ─────────────────────────────────────────────────────────────────────────
-- One row per (conversation, user) — a person's membership of a thread, plus their per-thread
-- read cursor and mute/removal state.
--
--   conversation_id  FK to conversation(id), ON DELETE CASCADE: a removed thread takes its
--                    membership rows with it.
--   user_id          FK to users(id), ON DELETE CASCADE. Accounts are only ever soft-deleted
--                    in-app, so membership rows survive an account tombstone; readers resolve
--                    people through the User aggregate (which hides tombstoned accounts), never
--                    through this table.
--   role             MEMBER | ADMIN, VARCHAR via EnumType.STRING. ADMIN can moderate the thread
--                    (soft-delete messages); the broadcaster/organiser is an ADMIN member.
--   mute             NONE | READ_ONLY | REMOVED, VARCHAR via EnumType.STRING, DEFAULT 'NONE'.
--                    READ_ONLY = the member may read but not post; REMOVED = kicked (kept as a row
--                    so a re-add / audit is clean, and so fan-out can skip them) — the moderation
--                    lever the group-chat epic (TM-433) drives. Enforced in the service, not here.
--   last_read_at     The member's read cursor: messages created after it are unread. NULL = the
--                    member has never read the thread (everything is unread). Drives the unread
--                    badge the read API (TM-436) surfaces.
--   joined_at        DB-authoritative join instant (now()), read-only — the membership order.
CREATE TABLE conversation_member (
    id              BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT      NOT NULL REFERENCES conversation (id) ON DELETE CASCADE,
    user_id         BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role            VARCHAR(16) NOT NULL,
    mute            VARCHAR(16) NOT NULL DEFAULT 'NONE',
    last_read_at    TIMESTAMPTZ,
    joined_at       TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- One membership per user per thread; a duplicate add surfaces as a unique violation for the
    -- membership API to map. Also the index that serves "members of a conversation" (its
    -- conversation_id prefix) and the fan-out's per-thread recipient scan.
    CONSTRAINT uq_conversation_member_conv_user UNIQUE (conversation_id, user_id)
);

-- "Conversations for a user" (the user's thread list) and the push fan-out's "which threads is this
-- user in" are both user_id lookups — required index.
CREATE INDEX idx_conversation_member_user_id ON conversation_member (user_id);

-- ── message ─────────────────────────────────────────────────────────────────────────────────────
-- One row per posted message in a thread. Immutable once written except for the moderation
-- soft-delete (deleted_at) — the group-chat epic never hard-deletes a message.
--
--   conversation_id  FK to conversation(id), ON DELETE CASCADE: messages of a removed thread go too.
--   sender_id        FK to users(id); NULL = a system / admin "from TeamMarhaba" message (an admin
--                    broadcast, or an in-thread system notice). No ON DELETE action — accounts are
--                    only ever soft-deleted, so the FK never fires (same convention as
--                    events.created_by); a human author is always resolved through the User
--                    aggregate, never assumed present here.
--   body             The message text as posted.
--   deep_link        Optional in-app route the message opens (e.g. /events/42); NULL if none —
--                    same convention/width as notification.deep_link.
--   created_at       DB-authoritative timestamp (now()), read back after insert — the in-thread
--                    ordering key (with id as the deterministic same-instant tiebreak).
--   deleted_at       Moderation soft-delete: NULL = live, non-NULL = removed by an admin. The row
--                    is kept (a struck-through "message removed" placeholder) rather than vanished,
--                    and every read filters `deleted_at IS NULL`.
CREATE TABLE message (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT        NOT NULL REFERENCES conversation (id) ON DELETE CASCADE,
    sender_id       BIGINT        REFERENCES users (id),
    body            VARCHAR(4000) NOT NULL,
    deep_link       VARCHAR(255),
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ
);

-- The dominant read is a thread's timeline in time order (oldest→newest to render, newest-first to
-- page and to find the last-message preview), and the unread count is "messages in this thread
-- created after my last_read_at" — all (conversation_id, created_at) scans. Required index.
CREATE INDEX idx_message_conversation_created_at ON message (conversation_id, created_at);
