-- V28__message_reactions — light-touch emoji reactions on a chat message (TM-461 / group-event-chat)
--
-- A reaction is a member's single tap on a message: an emoji they attach without posting a full
-- message ("react without replying"). The event-chat epic (TM-433) needs this as the lightweight
-- interaction on top of the shared message store (TM-435, V27). A "like" is NOT a separate concept
-- or table — it is simply this same row with the app's default emoji (❤️), so the client's
-- double-tap is a default-emoji react through exactly this mechanism.
--
-- Flyway owns this DDL; Hibernate runs validate-only, so the MessageReaction entity must match this
-- table exactly (column names, nullability, enum-as-VARCHAR conventions). Conventions reused from
-- the existing schema (see V27): BIGINT identity PK, TIMESTAMPTZ with a DB-authoritative
-- `created_at DEFAULT now()`, and people/messages held as plain FK ids.

-- ── message_reaction ──────────────────────────────────────────────────────────────────────────────
-- One row per (message, user, emoji): "this user reacted to this message with this emoji".
--
--   message_id  FK to message(id), ON DELETE CASCADE — mirrors message.conversation_id: a hard-removed
--               message takes its reactions with it. Messages are only ever soft-deleted (deleted_at)
--               in-app, so in practice the cascade never fires; reads of a soft-deleted message (and
--               therefore its reactions) are filtered out at the service layer.
--   user_id     FK to users(id), no ON DELETE action — same convention as message.sender_id: accounts
--               are only ever soft-deleted (tombstoned), so the FK never fires; the reacting person is
--               always resolved through the User aggregate, never assumed present from this row.
--   emoji       The reaction glyph as the client sends it — a unicode emoji (possibly a multi-codepoint
--               ZWJ sequence) or a `:shortcode:`. VARCHAR(32) comfortably holds either. Stored verbatim;
--               the app's default-like emoji is just one of the values that can land here.
--   created_at  DB-authoritative (now()), read back after insert — gives the reaction chips a stable
--               "first reacted first" order without trusting a caller-supplied timestamp.
CREATE TABLE message_reaction (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT      NOT NULL REFERENCES message (id) ON DELETE CASCADE,
    user_id    BIGINT      NOT NULL REFERENCES users (id),
    emoji      VARCHAR(32) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- One reaction per (message, user, emoji): a user cannot duplicate the SAME emoji on a message
    -- (a second identical react is a no-op / idempotent toggle-on), but may add several DIFFERENT
    -- emojis. A concurrent duplicate insert surfaces as a unique violation the service treats as
    -- "already reacted". The (message_id) prefix of this index also serves the dominant read — the
    -- per-message reaction summary — so no separate index on message_id is needed.
    CONSTRAINT uq_message_reaction UNIQUE (message_id, user_id, emoji)
);
