-- V2__create_users — TeamMarhaba accounts (TM-103 / 2.4.1)
--
-- The durable home for accounts. Identity is the Firebase UID from the verified ID token
-- (TM-79) — `firebase_uid` is the natural key. Rows are provisioned just-in-time on first
-- login (TM-112); `role` is mirrored from the Firebase custom claim (TM-110). Flyway owns
-- this DDL; Hibernate runs validate-only, so the `User` entity must match it exactly.
--
-- created_at/updated_at exist now (DB-managed defaults) but are mapped onto the entity later,
-- when the reusable auditing/optimistic-lock base lands (TM-114).
CREATE TABLE users (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firebase_uid VARCHAR(128) NOT NULL UNIQUE,
    email        VARCHAR(320),
    display_name VARCHAR(255),
    role         VARCHAR(32)  NOT NULL DEFAULT 'USER',
    enabled      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_users_email ON users (email);
