-- V35__create_membership — one membership per account (TM-474 / epic Membership)
--
-- Every account gets exactly one membership, JIT-enrolled on first sight (like the users row itself,
-- TM-112/TM-597) so entitlements + billing (later slices) hang off a guaranteed row. This slice ships
-- the tier only; the paid-upgrade payment gate (Revolut, TM-478) and the free-event credit *ledger*
-- (TM-477 consume/reverse) land on top of this table later. Flyway owns this DDL; Hibernate runs
-- validate-only, so the Membership entity must match these columns exactly.
--
--   user_id                  FK to users(id), UNIQUE — exactly one membership per account. ON DELETE
--                            CASCADE: a removed account has no membership to bill. The unique
--                            constraint is also what serialises a concurrent first-request burst
--                            (two /me reads racing to enrol) — the loser's INSERT trips it and re-reads
--                            the winner, mirroring users_firebase_uid_key (TM-597).
--   tier                     PAY_PER_EVENT | MONTHLY | DIAMOND. Stored as VARCHAR via Hibernate
--                            EnumType.STRING (same convention as users.role / users.notification_pref)
--                            so tiers can be added without a DB type change. DEFAULT 'PAY_PER_EVENT' —
--                            every new account starts pay-per-event; the entity provides the same value
--                            on insert, so the DB default only backstops out-of-band inserts.
--   first_event_credit_used  Whether this account's one first-event freebie has been spent. NOT NULL
--                            DEFAULT false — a freshly enrolled account has its first-event credit
--                            available. GET /me/membership surfaces the negation
--                            (firstEventCreditAvailable). The actual consume-on-commitment / reverse-on-
--                            in-window-cancel logic lives in checkout (TM-477); this column is the flag
--                            it flips.
--   created_at/updated_at    created_at is DB-authoritative (DEFAULT now(), read-only on the entity);
--                            updated_at is app-managed (set on enrol, bumped on every tier change).
--   version                  Optimistic-lock counter; Hibernate bumps it on update and rejects stale
--                            writes (mirrors users.version / events.version).
CREATE TABLE membership (
    id                      BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT      NOT NULL UNIQUE REFERENCES users (id) ON DELETE CASCADE,
    tier                    VARCHAR(32) NOT NULL DEFAULT 'PAY_PER_EVENT',
    first_event_credit_used BOOLEAN     NOT NULL DEFAULT false,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    version                 BIGINT      NOT NULL DEFAULT 0
);
