-- V36__create_orders — RSVP checkout order records + first-event credit ledger (TM-477 / epic Membership)
--
-- RSVP now goes through a checkout that resolves the caller's entitlement (TM-476) and records an
-- *order* — the durable receipt of what a commitment cost and where it stands. Free/included commitments
-- are frictionless (a £0 CONFIRMED order); a PAY commitment writes a PENDING order the Revolut path
-- (TM-478) later confirms/refunds. Flyway owns this DDL; Hibernate runs validate-only, so the Order and
-- Membership entities must match these columns exactly.
--
-- orders
--   user_id / event_id   FK to users(id) / events(id), both ON DELETE CASCADE — an order has no meaning
--                        once either party is gone. UNIQUE (user_id, event_id) is the idempotency key:
--                        a repeat checkout for the same (user, event) returns the existing order, never a
--                        duplicate, and a first-request race collapses to one row (the loser trips the
--                        constraint and re-reads the winner — mirroring membership_user_id_key, TM-597).
--   amount_pence         What the commitment costs in pence (minor units, GBP). 0 for FREE/INCLUDED, the
--                        entitlement's amount for PAY. CHECK (>= 0) — an order is never negative.
--   status               PENDING | CONFIRMED | CANCELLED | REFUND_DUE, stored as VARCHAR via Hibernate
--                        EnumType.STRING (same convention as membership.tier / users.role) so states can
--                        be added without a DB type change. FREE/INCLUDED land CONFIRMED; PAY lands
--                        PENDING (awaiting TM-478); an in-window cancel moves an order to CANCELLED, or to
--                        REFUND_DUE when real money was taken (the money refund itself is TM-478's job).
--   created_at/updated_at  created_at is DB-authoritative (DEFAULT now(), read-only on the entity);
--                        updated_at is app-managed (set on insert, bumped on every status change).
--   version              Optimistic-lock counter; Hibernate bumps it on update and rejects stale writes
--                        (mirrors membership.version / events.version) so two cancels can't both reverse.
CREATE TABLE orders (
    id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    event_id     BIGINT      NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    amount_pence INTEGER     NOT NULL CHECK (amount_pence >= 0),
    status       VARCHAR(32) NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    version      BIGINT      NOT NULL DEFAULT 0,
    UNIQUE (user_id, event_id)
);

-- First-event credit ledger (TM-474 flag -> TM-477 ledger). The boolean first_event_credit_used already
-- records *whether* the one freebie is spent; checkout additionally records *which* event consumed it and
-- *when*, so an in-window cancel of exactly that event can reverse the credit (and only that event's
-- cancel returns it). Both nullable: null = the credit is available (or was reversed). Kept on membership
-- rather than derived from the order so the reversal reads a single authoritative pointer.
ALTER TABLE membership ADD COLUMN first_event_credit_event_id   BIGINT;
ALTER TABLE membership ADD COLUMN first_event_credit_consumed_at TIMESTAMPTZ;
