-- V38__create_subscriptions — recurring membership billing (TM-620 / epic Membership)
--
-- MONTHLY (£9.99/mo) and DIAMOND (£19.99/mo) stop being free states: a paid tier is now backed by a
-- SUBSCRIPTION — the durable record of a recurring monthly charge against a saved card. The first
-- charge happens in a dedicated Subscribe checkout (Revolut widget, card saved for merchant-initiated
-- use); every renewal is charged OFF-SESSION by the renewal scheduler (SubscriptionRenewalScheduler).
-- Flyway owns this DDL; Hibernate runs validate-only, so the Subscription / SubscriptionCharge
-- entities must match these columns exactly.
--
-- subscriptions — at most ONE per account (UNIQUE user_id), the account's recurring-billing state.
--   user_id                   FK to users(id), UNIQUE, ON DELETE CASCADE — a removed account has
--                             nothing left to bill. One row per account: re-subscribing after a
--                             cancel RESETS this row rather than inserting a second (the charge rows
--                             below keep the history).
--   tier                      MONTHLY | DIAMOND — which paid tier this subscription pays for. Stored
--                             as VARCHAR via EnumType.STRING (same convention as membership.tier).
--   status                    ACTIVE | PAST_DUE | CANCELED (the TM-620 contract):
--                               ACTIVE   — renewing normally; the tier is fully paid for.
--                               PAST_DUE — a renewal failed; dunning retries are in flight and the
--                                          tier is kept while we retry (retry_count / next_charge_at).
--                               CANCELED — renewals stopped (user cancel, or dunning exhausted). The
--                                          tier survives until current_period_end, then the scheduler
--                                          downgrades the membership to PAY_PER_EVENT.
--   current_period_start/end  the paid-for window. The billing cycle is ROLLING from the subscribe
--                             date (anniversary billing): each successful renewal advances the window
--                             by one calendar month from the previous period END (not from the charge
--                             time), so a dunning-delayed charge never drifts the anniversary.
--   saved_payment_method_ref  the provider's saved payment-method id (Revolut payment method UUID,
--                             saved for MERCHANT use by the first checkout) — the handle every
--                             off-session renewal charges. NULL until the save is confirmed; a NULL at
--                             renewal time is re-fetched from the provider (and treated as a failed
--                             attempt if the customer has no merchant-saved method).
--   provider                  which payment gateway holds the mandate ('revolut'), mirroring
--                             orders.provider so a second provider needs no DB change.
--   provider_customer_id      the provider's customer id (Revolut Customer UUID) the saved card hangs
--                             off — needed to create renewal orders and to (re)list saved methods.
--   next_charge_at            when the scheduler must next act on this row (the single "due" pointer):
--                             the period end for an ACTIVE row (renewal), the retry time for a
--                             PAST_DUE row (dunning), the period end for a CANCELED row (downgrade),
--                             and NULL when nothing is pending (fully lapsed/downgraded). Indexed —
--                             it is the renewal scan's WHERE clause.
--   retry_count               dunning retries attempted so far in the CURRENT past-due episode; reset
--                             to 0 on every successful charge.
--   canceled_at               when renewals were stopped (user cancel or dunning exhaustion); NULL
--                             while renewing.
--   created_at/updated_at     created_at is DB-authoritative (DEFAULT now(), read-only on the
--                             entity); updated_at is app-managed (bumped on every state change).
--   version                   optimistic-lock counter (mirrors membership.version / orders.version).
CREATE TABLE subscriptions (
    id                       BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                  BIGINT      NOT NULL UNIQUE REFERENCES users (id) ON DELETE CASCADE,
    tier                     VARCHAR(32) NOT NULL,
    status                   VARCHAR(32) NOT NULL,
    current_period_start     TIMESTAMPTZ NOT NULL,
    current_period_end       TIMESTAMPTZ NOT NULL,
    saved_payment_method_ref VARCHAR(255),
    provider                 VARCHAR(32),
    provider_customer_id     VARCHAR(255),
    next_charge_at           TIMESTAMPTZ,
    retry_count              INTEGER     NOT NULL DEFAULT 0,
    canceled_at              TIMESTAMPTZ,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    version                  BIGINT      NOT NULL DEFAULT 0
);

-- The renewal scan's lookup: "every subscription whose next_charge_at has passed". Partial — rows
-- with nothing pending (next_charge_at IS NULL) don't clutter the index.
CREATE INDEX subscriptions_next_charge_at_idx
    ON subscriptions (next_charge_at)
    WHERE next_charge_at IS NOT NULL;

-- subscription_charges — one row per subscription charge ATTEMPT (the admin-visible billing history
-- and the webhook reconciliation ledger). Kept separate from `orders` (that table is the per-event
-- ticket ledger with a NOT NULL event_id + UNIQUE (user_id, event_id) — a monthly charge has no
-- event). Keyed by user_id rather than a subscription FK so the history SURVIVES a re-subscribe
-- resetting the subscriptions row.
--   kind               INITIAL (the Subscribe checkout's first charge, paid in-browser via the widget
--                      with SCA/3DS) | RENEWAL (an off-session merchant-initiated charge by the
--                      scheduler).
--   status             PENDING (created, money not yet confirmed) | PAID | FAILED. An INITIAL charge
--                      is confirmed PENDING → PAID by the provider webhook; a RENEWAL is settled
--                      synchronously by the pay-order call (webhook confirmation is the idempotent
--                      backstop that can also heal a FAILED row the provider later reports paid).
--   tier/amount_pence  what was (to be) charged: the tier and its monthly price in pence at charge
--                      time — a later price change never rewrites history.
--   provider/provider_order_id  which gateway + its permanent order id (the webhook match key).
--                      UNIQUE partial index, exactly like orders.provider_order_id, so a replayed
--                      webhook resolves to at most one charge.
--   provider_customer_id  the provider customer the charge's order was created against — carried on
--                      the INITIAL charge so the webhook-driven activation knows which customer the
--                      saved card lives on (the subscriptions row may not exist yet at charge time).
--   period_start/end   the paid-for window this charge covers (NULL until known for an INITIAL
--                      charge — the period anchors on the moment the payment settles).
--   created_at/updated_at/version  same conventions as every other table.
CREATE TABLE subscription_charges (
    id                BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    kind              VARCHAR(32) NOT NULL,
    status            VARCHAR(32) NOT NULL,
    tier              VARCHAR(32) NOT NULL,
    amount_pence      INTEGER     NOT NULL CHECK (amount_pence >= 0),
    provider          VARCHAR(32),
    provider_order_id VARCHAR(255),
    provider_customer_id VARCHAR(255),
    period_start      TIMESTAMPTZ,
    period_end        TIMESTAMPTZ,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    version           BIGINT      NOT NULL DEFAULT 0
);

-- Webhook reconciliation key: a provider order id maps to at most one charge (partial unique — the
-- many rows that never reached the provider keep NULL, which the partial index allows any number of).
CREATE UNIQUE INDEX subscription_charges_provider_order_id_key
    ON subscription_charges (provider_order_id)
    WHERE provider_order_id IS NOT NULL;

-- The admin history read: a user's charges newest-first.
CREATE INDEX subscription_charges_user_id_idx
    ON subscription_charges (user_id, created_at DESC);
