-- V41__create_venues — reusable venue/location library + the events → venue reference (TM-519 / epic Events MVP)
--
-- Event location used to be typed as free text on every create (events.location_text). This slice
-- introduces a reusable *Venue* — a named place with a full address, geo hint, photo and a set of
-- optional details (capacity, accessibility, parking, indoor/outdoor, map link, city/area) — that the
-- admin creates once and the event-create form then *references*. Edit a venue once and every event
-- pointing at it reflects the change (the event stores a reference, not a copied string). Flyway owns
-- this DDL; Hibernate runs validate-only, so the Venue entity + the events mapping must match exactly.
--
--   name            Display name of the place (required), e.g. "Marhaba Community Hall".
--   address_line    Full street address on one line (required) — the exact location. Only the admin
--                   venues API (admin-only) ever exposes it; the PUBLIC event surface still gates the
--                   exact location behind the TM-408 reveal window (it renders events.location_text,
--                   not this row), so referencing a venue never leaks its address early.
--   city            Optional coarse locality / area tag, e.g. "London" — the searchable, pre-reveal
--                   hint dimension (mirrors events.city). NULL = no area tag.
--   latitude/longitude  Optional geo coordinates (WGS84 decimal degrees) for a map pin. Both NULL =
--                   no pin. DOUBLE PRECISION maps to the entity's Double.
--   map_url         Optional map-pin link (Google/Apple Maps etc.); NULL if none.
--   notes           Optional free-text description / directions (up to ~5000 chars, the same body cap
--                   the app uses elsewhere). NULL = none.
--   capacity        Optional headline capacity of the place; CHECK (>= 1) when set. NULL = unspecified.
--   accessibility   Optional accessibility notes (step-free access, accessible toilets, …). NULL = none.
--   parking         Optional parking notes. NULL = none.
--   indoor_outdoor  Optional INDOOR | OUTDOOR | MIXED, stored as VARCHAR via Hibernate EnumType.STRING
--                   (same convention as events.status / users.role) so values can be added without a DB
--                   type change. NULL = unspecified.
--   photo_path      Optional Firebase Storage object path of the venue photo (the house avatar/image
--                   pattern, TM-166: the console uploads venue-images/{venueId} directly to Storage —
--                   admin-only per storage.rules — and we persist only the path). NULL = no photo.
--   active          Whether the venue is offered in the event-create picker. NOT NULL DEFAULT true. A
--                   *deactivate* flips this to false (retire a place without hard-deleting it — a past
--                   event may still reference it); the admin console still lists inactive venues and can
--                   reactivate. This is the ticket's "deactivate, don't hard-delete" rule.
--   created_by      users.id of the creating admin (FK). Resolve the person through UserRepository.
--   created_at/updated_at  created_at is DB-authoritative (DEFAULT now(), read-only on the entity);
--                   updated_at is app-managed (set on create, bumped on every mutation).
--   deleted_at      Soft-delete marker (the house @SQLRestriction pattern, TM-114): NULL = active row,
--                   non-null = tombstoned + hidden from every normal query. Distinct from `active` —
--                   this ticket never hard/soft-deletes venues (retire via `active`), but the column +
--                   restriction keep the venue on the same lifecycle contract as every other aggregate.
--   version         Optimistic-lock counter; Hibernate bumps it on update and rejects stale writes
--                   (mirrors events.version / users.version).
CREATE TABLE venues (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(160)  NOT NULL,
    address_line   VARCHAR(500)  NOT NULL,
    city           VARCHAR(120),
    latitude       DOUBLE PRECISION,
    longitude      DOUBLE PRECISION,
    map_url        VARCHAR(2048),
    notes          VARCHAR(5000),
    capacity       INTEGER       CHECK (capacity IS NULL OR capacity >= 1),
    accessibility  VARCHAR(1000),
    parking        VARCHAR(1000),
    indoor_outdoor VARCHAR(16),
    photo_path     VARCHAR(512),
    active         BOOLEAN       NOT NULL DEFAULT true,
    created_by     BIGINT        NOT NULL REFERENCES users (id),
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    deleted_at     TIMESTAMPTZ,
    version        BIGINT        NOT NULL DEFAULT 0
);

-- The admin console lists the full inventory but the picker only offers active venues; index the flag.
CREATE INDEX idx_venues_active ON venues (active);
-- Search matches name/city case-insensitively; index the normalized city for the area-tag filter.
CREATE INDEX idx_venues_city ON venues (lower(city));

-- Events reference a reusable venue (TM-519). NULLABLE by design: legacy events and one-off free-text
-- locations (an admin can still type a location that isn't a saved venue) keep working with venue_id
-- NULL — the back-compat guarantee. events.location_text stays NOT NULL as the denormalized display
-- line (the picker fills it from the chosen venue), so nothing that reads location_text changes.
-- ON DELETE SET NULL: retiring is done via venues.active, but were a venue ever hard-deleted, its
-- events simply detach (reference cleared) rather than cascade-deleting real events.
ALTER TABLE events ADD COLUMN venue_id BIGINT REFERENCES venues (id) ON DELETE SET NULL;
CREATE INDEX idx_events_venue_id ON events (venue_id);
