-- V45__create_interests — interests catalogue + free-text user snapshot + runtime app-config store (TM-773 / epic Interests)
--
-- The foundation slice (I1) of the interests feature: the data layer + seed only, no user-facing UI
-- and no admin write endpoints (those land in later sub-tickets I2/I4/I6/I7). Three tables ship here:
--
--   1. interest_catalogue — the admin-managed MASTER LIST of pickable interests (label, category,
--      a highlight flag + a sort weight for floating popular ones to the top). An aggregate on the
--      same lifecycle contract as venues/events: soft-delete via deleted_at + the house
--      @SQLRestriction("deleted_at is null") (TM-114) hides a tombstoned row from every normal query,
--      while a separate visible `active` flag is the "offered to users" switch. Retiring an interest =
--      stamp deleted_at AND/OR set active=false — the row is KEPT, never hard-deleted, so any user who
--      already picked it is unaffected (see table 2). updated_at is app-managed (set on create, bumped
--      on every mutation) and `version` is the optimistic-lock counter — both present from day one even
--      though I1 ships no mutation path, so the aggregate is on the same contract as the others when the
--      admin write endpoint (I2) lands.
--
--   2. user_interest — a per-user FREE-TEXT SNAPSHOT of the interests a user picked. CRITICAL DESIGN:
--      label and category are TEXT COPIES taken at pick time and are deliberately DECOUPLED from the
--      catalogue's current state. source_interest_id is a plain BIGINT provenance hint with NO FOREIGN
--      KEY — so editing, retiring (soft-delete / active=false), or even hard-deleting a catalogue row
--      leaves the user's saved label/category/source_interest_id COMPLETELY UNCHANGED. There is no
--      ON DELETE CASCADE and no ON DELETE SET NULL touching that column, because either would let a
--      catalogue change mutate or remove a user's saved snapshot. (user_id, by contrast, IS a real FK
--      to users with ON DELETE CASCADE — this is per-user data that should die with a hard-removed
--      account, exactly like device_tokens / notifications.) This is an append-only snapshot log, so
--      it has no deleted_at and no version, mirroring event_attendance; edit/replace semantics belong
--      to later tickets.
--
--   3. app_config — the first mutable, admin-editable RUNTIME config store (no such store existed). A
--      minimal key/value table seeded here with the interests min/max-selections defaults. I1 ships the
--      storage + a read path (AppConfigService) + the two seed rows only; the admin WRITE endpoint that
--      lets these be changed at runtime is TM-773's follow-up I2 and is explicitly OUT OF SCOPE here.
--      `version` is present so that future write path gets optimistic locking for free.
--
-- Flyway owns all this DDL; Hibernate runs validate-only, so the InterestCatalogue / UserInterest /
-- AppConfig entities must match these tables exactly.

-- ---------------------------------------------------------------------------------------------------
-- 1. interest_catalogue — admin master list
-- ---------------------------------------------------------------------------------------------------
--   label        Display label of the interest, e.g. "Coffee & cafés" (required). Unique among ACTIVE
--                (non-tombstoned) rows only — see the partial-unique index below.
--   category     The grouping bucket, e.g. "Food & Drink" (required). One of the seven seed categories.
--   highlighted  Whether the interest is featured (bool, DEFAULT false). The six seed highlights float
--                to the top of the picker via a higher sort_weight.
--   sort_weight  Ordering weight (int, DEFAULT 0). Higher sorts first; the listing is
--                ORDER BY sort_weight DESC, label. Highlighted seed rows get 100, all others 0.
--   active       Whether the interest is offered to users (bool, DEFAULT true). Retire without deleting
--                by flipping this to false — a distinct, visible flag from the deleted_at tombstone.
--   created_at   DB-authoritative creation timestamp (DEFAULT now()); read-only on the entity.
--   updated_at   App-managed: set on create and bumped on every mutation (mirrors venues).
--   deleted_at   Soft-delete marker (the house @SQLRestriction pattern, TM-114): NULL = active row,
--                non-null = tombstoned + hidden from every normal query. Distinct from `active`.
--   version      Optimistic-lock counter (mirrors venues.version / events.version).
CREATE TABLE interest_catalogue (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label        VARCHAR(120) NOT NULL,
    category     VARCHAR(80)  NOT NULL,
    highlighted  BOOLEAN      NOT NULL DEFAULT false,
    sort_weight  INTEGER      NOT NULL DEFAULT 0,
    active       BOOLEAN      NOT NULL DEFAULT true,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at   TIMESTAMPTZ,
    version      BIGINT       NOT NULL DEFAULT 0
);

-- label is unique among ACTIVE (non-tombstoned) rows only, so a retired label can be re-added later.
-- Partial unique index keyed on deleted_at IS NULL — the house pattern (cf. uq_conversation_event_id
-- in V27, which is likewise a partial unique index).
CREATE UNIQUE INDEX uq_interest_catalogue_label_active
    ON interest_catalogue (label) WHERE deleted_at IS NULL;

-- The catalogue listing sorts highlights/popular first (higher sort_weight first), then alphabetically.
CREATE INDEX idx_interest_catalogue_sort ON interest_catalogue (sort_weight DESC, label);
CREATE INDEX idx_interest_catalogue_active ON interest_catalogue (active);

-- ---------------------------------------------------------------------------------------------------
-- 2. user_interest — per-user free-text snapshot (deliberately NOT FK-linked to the catalogue)
-- ---------------------------------------------------------------------------------------------------
--   user_id             REAL FK to users(id) ON DELETE CASCADE — this is per-user data that should die
--                       with a hard-removed account (a soft-delete/deleted_at tombstone never fires the
--                       cascade, so rows survive an account tombstone; the entity still stores this as a
--                       plain Long, not a JPA association, to stay decoupled from User's @SQLRestriction).
--   label               TEXT COPY of the catalogue label at pick time — the user's own free-text
--                       snapshot, independent of the catalogue's current state.
--   category            TEXT COPY of the catalogue category at pick time. Also independent.
--   source_interest_id  Plain BIGINT provenance hint, NO REFERENCES / NO FK CONSTRAINT — deliberately
--                       NOT a foreign key. Editing, retiring, or hard-deleting the source catalogue row
--                       leaves this (and label/category) UNCHANGED: no cascade, no set-null, ever.
--   created_at          DB-authoritative pick instant (DEFAULT now()); read-only on the entity.
-- No deleted_at / no version: this is an append-only immutable snapshot log (mirrors event_attendance).
CREATE TABLE user_interest (
    id                 BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    label              TEXT        NOT NULL,
    category           TEXT        NOT NULL,
    source_interest_id BIGINT, -- soft provenance pointer only; intentionally NOT a FK (see header)
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_user_interest_user_id ON user_interest (user_id);

-- ---------------------------------------------------------------------------------------------------
-- 3. app_config — minimal mutable runtime key/value config store
-- ---------------------------------------------------------------------------------------------------
--   config_key    The setting key, e.g. "interests.max_selections" (required, globally UNIQUE).
--   config_value  The setting value as text (required). Typed reads (int etc.) parse it at read time.
--   description   Optional human-readable note on what the setting does.
--   created_at    DB-authoritative creation timestamp (DEFAULT now()); read-only on the entity.
--   updated_at    App-managed: set on create, bumped on every mutation (the future I2 write path).
--   version       Optimistic-lock counter — present so the I2 admin write path gets locking for free.
CREATE TABLE app_config (
    id           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key   VARCHAR(120) NOT NULL UNIQUE,
    config_value VARCHAR(500) NOT NULL,
    description  VARCHAR(500),
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version      BIGINT       NOT NULL DEFAULT 0
);

-- Seed the interests min/max-selection defaults (min=1, max=3). The admin write endpoint that lets
-- these be changed at runtime is I2 (out of scope for I1); I1 ships only these rows + the read path.
INSERT INTO app_config (config_key, config_value, description) VALUES
  ('interests.min_selections', '1', 'Minimum number of interests a user must select'),
  ('interests.max_selections', '3', 'Maximum number of interests a user may select');

-- ---------------------------------------------------------------------------------------------------
-- Seed the 101 catalogue interests (single atomic multi-row INSERT).
-- highlighted = true for exactly six (Coffee & cafés, Hiking & rambling, Walking, Padel, Badminton,
-- Running & jogging); those get sort_weight = 100 so they float to the top of the
-- ORDER BY sort_weight DESC, label listing. All other rows are highlighted = false, sort_weight = 0.
-- active = true for every seed row. Note: `Walking` (Outdoors & Nature) is a distinct, highlighted
-- interest, separate from `Hiking & rambling`, `Walk & talk`, and `Dog walks` — all four exist.
-- ---------------------------------------------------------------------------------------------------
INSERT INTO interest_catalogue (label, category, highlighted, sort_weight, active) VALUES
  -- Sport & Fitness (15)
  ('Five-a-side football',   'Sport & Fitness', false,   0, true),
  ('Running & jogging',      'Sport & Fitness', true,  100, true),
  ('Parkrun',                'Sport & Fitness', false,   0, true),
  ('Cycling',                'Sport & Fitness', false,   0, true),
  ('Gym & weightlifting',    'Sport & Fitness', false,   0, true),
  ('Yoga',                   'Sport & Fitness', false,   0, true),
  ('Pilates',                'Sport & Fitness', false,   0, true),
  ('Swimming',               'Sport & Fitness', false,   0, true),
  ('Tennis',                 'Sport & Fitness', false,   0, true),
  ('Badminton',              'Sport & Fitness', true,  100, true),
  ('Padel',                  'Sport & Fitness', true,  100, true),
  ('Climbing & bouldering',  'Sport & Fitness', false,   0, true),
  ('Martial arts',           'Sport & Fitness', false,   0, true),
  ('Netball',                'Sport & Fitness', false,   0, true),
  ('Basketball',             'Sport & Fitness', false,   0, true),
  -- Outdoors & Nature (15)
  ('Hiking & rambling',      'Outdoors & Nature', true,  100, true),
  ('Dog walks',              'Outdoors & Nature', false,   0, true),
  ('Wild swimming',          'Outdoors & Nature', false,   0, true),
  ('Kayaking & paddleboarding', 'Outdoors & Nature', false, 0, true),
  ('Camping',                'Outdoors & Nature', false,   0, true),
  ('Cycling tours',          'Outdoors & Nature', false,   0, true),
  ('Gardening',              'Outdoors & Nature', false,   0, true),
  ('Birdwatching',           'Outdoors & Nature', false,   0, true),
  ('Foraging',               'Outdoors & Nature', false,   0, true),
  ('Photography walks',      'Outdoors & Nature', false,   0, true),
  ('Star-gazing',            'Outdoors & Nature', false,   0, true),
  ('Geocaching',             'Outdoors & Nature', false,   0, true),
  ('Fishing',                'Outdoors & Nature', false,   0, true),
  ('Nature conservation',    'Outdoors & Nature', false,   0, true),
  ('Walking',                'Outdoors & Nature', true,  100, true),
  -- Food & Drink (14)
  ('Coffee & cafés',         'Food & Drink', true,  100, true),
  ('Brunch',                 'Food & Drink', false,   0, true),
  ('Cooking',                'Food & Drink', false,   0, true),
  ('Baking',                 'Food & Drink', false,   0, true),
  ('Wine tasting',           'Food & Drink', false,   0, true),
  ('Craft beer',             'Food & Drink', false,   0, true),
  ('Cocktails',              'Food & Drink', false,   0, true),
  ('Vegan & veggie',         'Food & Drink', false,   0, true),
  ('Street food',            'Food & Drink', false,   0, true),
  ('BBQ & grilling',         'Food & Drink', false,   0, true),
  ('Supper clubs',           'Food & Drink', false,   0, true),
  ('Pub food',               'Food & Drink', false,   0, true),
  ('Afternoon tea',          'Food & Drink', false,   0, true),
  ('Whisky & spirits',       'Food & Drink', false,   0, true),
  -- Arts & Creative (14)
  ('Photography',            'Arts & Creative', false,   0, true),
  ('Painting & drawing',     'Arts & Creative', false,   0, true),
  ('Pottery & ceramics',     'Arts & Creative', false,   0, true),
  ('Crafts & DIY',           'Arts & Creative', false,   0, true),
  ('Knitting & crochet',     'Arts & Creative', false,   0, true),
  ('Creative writing',       'Arts & Creative', false,   0, true),
  ('Poetry',                 'Arts & Creative', false,   0, true),
  ('Theatre',                'Arts & Creative', false,   0, true),
  ('Film & cinema',          'Arts & Creative', false,   0, true),
  ('Museums & galleries',    'Arts & Creative', false,   0, true),
  ('Calligraphy',            'Arts & Creative', false,   0, true),
  ('Jewellery making',       'Arts & Creative', false,   0, true),
  ('Sketching',              'Arts & Creative', false,   0, true),
  ('Sewing',                 'Arts & Creative', false,   0, true),
  -- Games & Tech (14)
  ('Board games',            'Games & Tech', false,   0, true),
  ('Video gaming',           'Games & Tech', false,   0, true),
  ('Chess',                  'Games & Tech', false,   0, true),
  ('Tabletop RPGs (D&D)',    'Games & Tech', false,   0, true),
  ('Card games',             'Games & Tech', false,   0, true),
  ('Trivia & pub quiz',      'Games & Tech', false,   0, true),
  ('Escape rooms',           'Games & Tech', false,   0, true),
  ('Puzzles & crosswords',   'Games & Tech', false,   0, true),
  ('Coding & hackathons',    'Games & Tech', false,   0, true),
  ('Tech meetups',           'Games & Tech', false,   0, true),
  ('AI & machine learning',  'Games & Tech', false,   0, true),
  ('Startups & founders',    'Games & Tech', false,   0, true),
  ('Retro gaming',           'Games & Tech', false,   0, true),
  ('Esports',                'Games & Tech', false,   0, true),
  -- Music & Nightlife (13)
  ('Live music & gigs',      'Music & Nightlife', false,   0, true),
  ('DJ & electronic',        'Music & Nightlife', false,   0, true),
  ('Karaoke',                'Music & Nightlife', false,   0, true),
  ('Open mic',               'Music & Nightlife', false,   0, true),
  ('Dancing & salsa',        'Music & Nightlife', false,   0, true),
  ('Festivals',              'Music & Nightlife', false,   0, true),
  ('Jazz',                   'Music & Nightlife', false,   0, true),
  ('Vinyl & records',        'Music & Nightlife', false,   0, true),
  ('Choir & singing',        'Music & Nightlife', false,   0, true),
  ('Learning an instrument', 'Music & Nightlife', false,   0, true),
  ('Clubbing',               'Music & Nightlife', false,   0, true),
  ('Music production',       'Music & Nightlife', false,   0, true),
  ('Folk & acoustic',        'Music & Nightlife', false,   0, true),
  -- Social & Wellbeing (16)
  ('Book club',              'Social & Wellbeing', false,   0, true),
  ('Language exchange',      'Social & Wellbeing', false,   0, true),
  ('Volunteering',           'Social & Wellbeing', false,   0, true),
  ('Networking',             'Social & Wellbeing', false,   0, true),
  ('New in town',            'Social & Wellbeing', false,   0, true),
  ('Parents & little ones',  'Social & Wellbeing', false,   0, true),
  ('50+ social',             'Social & Wellbeing', false,   0, true),
  ('Meditation & mindfulness', 'Social & Wellbeing', false, 0, true),
  ('Mental-health peer support', 'Social & Wellbeing', false, 0, true),
  ('Walk & talk',            'Social & Wellbeing', false,   0, true),
  ('Coffee & chat',          'Social & Wellbeing', false,   0, true),
  ('Charity & fundraising',  'Social & Wellbeing', false,   0, true),
  ('Faith & spirituality',   'Social & Wellbeing', false,   0, true),
  ('Breathwork',             'Social & Wellbeing', false,   0, true),
  ('Journaling',             'Social & Wellbeing', false,   0, true),
  ('Community gardening',    'Social & Wellbeing', false,   0, true);
