-- V4__create_audit_events — append-only audit log (TM-113 / 2.5.1)
--
-- "Who did what, when." Every significant action appends exactly one immutable row here via
-- AuditService.record(...). Reusable by every future entity; account actions wire in first.
--
-- Append-only BY DESIGN: the entity exposes no mutators, the repository declares no update/delete,
-- and no application path rewrites a row. (We deliberately do not also revoke UPDATE/DELETE at the
-- DB grant level here — the app runs as the schema owner in dev/test — but the app contract is
-- insert-and-read only.)
--
--   actor_uid    Firebase UID of the caller responsible (NULL for system/unattributed actions).
--   action       AuditAction enum name (stored as text).
--   target_type  the kind of thing acted on (e.g. 'User'); NULL if not entity-scoped.
--   target_id    identifier of the target (string, to stay entity-agnostic).
--   metadata     optional JSONB context. NEVER store secrets, tokens, or passwords in it.
--   created_at   DB-authoritative timestamp (now()), so the clock can't be set by the caller.
CREATE TABLE audit_events (
    id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_uid   VARCHAR(128),
    action      VARCHAR(64) NOT NULL,
    target_type VARCHAR(64),
    target_id   VARCHAR(128),
    metadata    JSONB,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Audit logs are read by actor ("what did this user do"), by target ("history of this account"),
-- and most-recent-first; index for those access patterns.
CREATE INDEX idx_audit_events_actor      ON audit_events (actor_uid);
CREATE INDEX idx_audit_events_target     ON audit_events (target_type, target_id);
CREATE INDEX idx_audit_events_created_at ON audit_events (created_at DESC);
