-- V54__create_cities — admin-managed city catalogue (TM-1089, epic wave-admin-events-city)
--
-- Replaces the hardcoded city list (CITY_OPTIONS in web/src/assets/profile-core.js:459,
-- ALLOWED_CITIES in backend UserService.java:75) with a rich, admin-managed record per city:
-- default icon (emoji) + country + geo point (lat/long) + a big empty-state image path. This is
-- the DATA-LAYER + BACKEND-API slice (model + migration + admin CRUD + public read + seed). The
-- web admin console (image/icon upload) and the picker cutover (retiring CITY_OPTIONS/
-- ALLOWED_CITIES) are deliberate follow-ups; the consumption of the icon (Events-tab heading) and
-- the big image (Home empty state) are STORE-ONLY here, per the ticket's Out-of-scope.
--
-- The aggregate follows the interest_catalogue contract exactly (V45): retire-not-delete via
-- deleted_at + the house @SQLRestriction("deleted_at is null") (TM-114) that hides a tombstoned row
-- from every normal query, PLUS a separate visible `active` flag ("offered to users"). Retiring a
-- city = stamp deleted_at AND active=false — the row is KEPT, never hard-deleted, so any user/event
-- already referencing a city name (a free-text copy, no FK) is untouched. updated_at is app-managed;
-- `version` is the optimistic-lock counter. Flyway owns this DDL; Hibernate runs validate-only, so
-- the CityCatalogue entity must match this table exactly.
--
--   name         Display name of the city, e.g. "London" (required). Unique among ACTIVE
--                (non-tombstoned) rows only — see the partial-unique index below.
--   country      The country the city sits in, e.g. "United Kingdom" (required, admin free-text).
--   icon_emoji   Default icon shown beside the city name (e.g. a flag glyph). NULLABLE by design —
--                a city without an icon is valid; the client falls back to no glyph (mirrors
--                interest_catalogue.emoji, TM-805). An uploaded-image icon is a later option.
--   geo_lat      Latitude of the city centre (decimal degrees, WGS-84), or NULL if unset.
--   geo_lng      Longitude of the city centre (decimal degrees, WGS-84), or NULL if unset.
--   image_path   Storage path of the big empty-state image (e.g. "city-images/london.jpg"), served
--                via downloadUrlForPath. NULLABLE — STORED here, not yet rendered on Home (deferred).
--   sort_weight  Ordering weight (int, DEFAULT 0). Higher sorts first; listing is
--                ORDER BY sort_weight DESC, name. The four seed cities carry descending weights so
--                they keep the current fixed order (London, Milton Keynes, Sharjah, Karachi).
--   active       Whether the city is offered to users (bool, DEFAULT true). Retire without deleting
--                by flipping this to false — distinct from the deleted_at tombstone.
--   created_at   DB-authoritative creation timestamp (DEFAULT now()); read-only on the entity.
--   updated_at   App-managed: set on create and bumped on every mutation (mirrors venues/interests).
--   deleted_at   Soft-delete marker (the house @SQLRestriction pattern, TM-114): NULL = active row,
--                non-null = tombstoned + hidden from every normal query. Distinct from `active`.
--   version      Optimistic-lock counter (mirrors interest_catalogue.version).
CREATE TABLE city_catalogue (
    id           BIGINT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(120)     NOT NULL,
    country      VARCHAR(80)      NOT NULL,
    icon_emoji   TEXT,
    geo_lat      DOUBLE PRECISION,
    geo_lng      DOUBLE PRECISION,
    image_path   VARCHAR(500),
    sort_weight  INTEGER          NOT NULL DEFAULT 0,
    active       BOOLEAN          NOT NULL DEFAULT true,
    created_at   TIMESTAMPTZ      NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ      NOT NULL DEFAULT now(),
    deleted_at   TIMESTAMPTZ,
    version      BIGINT           NOT NULL DEFAULT 0
);

-- name is unique among ACTIVE (non-tombstoned) rows only, so a retired name can be re-added later.
-- Partial unique index keyed on deleted_at IS NULL — the house pattern (cf.
-- uq_interest_catalogue_label_active in V45).
CREATE UNIQUE INDEX uq_city_catalogue_name_active
    ON city_catalogue (name) WHERE deleted_at IS NULL;

-- The catalogue listing sorts by weight (higher first) then alphabetically by name.
CREATE INDEX idx_city_catalogue_sort ON city_catalogue (sort_weight DESC, name);
CREATE INDEX idx_city_catalogue_active ON city_catalogue (active);

-- Seed the four current cities with icon + country + geo, preserving the existing fixed order
-- (London, Milton Keynes, Sharjah, Karachi) via descending sort_weight. image_path is left NULL —
-- the big empty-state images are uploaded later through the admin console. These four names match
-- the retired CITY_OPTIONS / ALLOWED_CITIES exactly, so existing users' saved city values keep
-- validating once the picker cutover lands.
INSERT INTO city_catalogue (name, country, icon_emoji, geo_lat, geo_lng, sort_weight, active) VALUES
  ('London',        'United Kingdom',        '🇬🇧', 51.5074,  -0.1278, 40, true),
  ('Milton Keynes', 'United Kingdom',        '🇬🇧', 52.0406,  -0.7594, 30, true),
  ('Sharjah',       'United Arab Emirates',  '🇦🇪', 25.3463,  55.4209, 20, true),
  ('Karachi',       'Pakistan',              '🇵🇰', 24.8607,  67.0011, 10, true);
