-- V56__create_event_series — recurring event series data model (TM-789 / recurring events v1, wave-admin-events-3)
--
-- A recurring *series* is the template + cadence an admin defines once, from which concrete `events`
-- occurrences are generated. THIS SLICE IS DATA-MODEL ONLY: no API, no UI, no recurrence engine (that
-- is TM-790). It creates the series table; V57 adds the events → series reference columns. Flyway owns
-- this DDL; Hibernate runs validate-only, so the EventSeries entity must match exactly.
--
-- v1 THIN CUT — DAILY + WEEKLY only. The model is kept extensible for wave-3b: `rrule_raw`,
-- `by_month_day` and `nth_weekday` are present but NEVER populated in v1 (they exist so the
-- monthly / nth-weekday cadences land in 3b without a schema change).
--
-- Recurrence rule
--   frequency        DAILY | WEEKLY, stored as VARCHAR via Hibernate EnumType.STRING (same convention
--                    as events.status / users.role) so MONTHLY etc. can be added without a type change.
--   interval_value   Every-N step (1 = every day/week, 2 = every other, …). NOT NULL DEFAULT 1,
--                    CHECK (>= 1). Named interval_value because INTERVAL is a reserved SQL type word.
--   by_weekday       WEEKLY only: ISO-8601 weekday to pin to (1=Mon … 7=Sun), CHECK 1..7 when set.
--                    NULL = inherit first_start_at's weekday. Unused (NULL) for DAILY. v1 = single
--                    weekday only (multi-weekday is 3b).
--   by_month_day     3b PLACEHOLDER (day-of-month for MONTHLY, 1..31 or -1 = last). NOT used in v1.
--   nth_weekday      3b PLACEHOLDER (nth weekday of month, e.g. "2nd Tuesday"). NOT used in v1.
--   rrule_raw        Optional raw RFC-5545 RRULE (NULL in v1) — the extensibility seam for 3b cadences
--                    the structured columns can't express.
--   timezone         IANA timezone id the recurrence is computed in (mirrors events.timezone).
--   first_start_at   UTC instant of the first occurrence's start — the anchor all occurrences derive from.
--   until_date       Optional LOCAL calendar end (inclusive), no time-of-day; NULL = open-ended.
--   occurrence_count Optional cap on total occurrences; NULL = uncapped. CHECK (>= 1) when set.
--   horizon_generated_until  Rolling generation watermark — occurrences materialised up to this UTC
--                    instant (the engine, TM-790, advances it). NULL = nothing generated yet.
--
-- Template snapshot (frozen copy of the EventDraft fields the engine stamps each occurrence from)
--   template_heading / template_description / template_location_text   Required text snapshot.
--   template_city / template_venue_id                                  Optional location snapshot.
--   template_capacity                                                  NULL = unlimited.
--   template_price_pence   Ticket price in pence (GBP minor units). NOT NULL DEFAULT 500 (£5), matching
--                          events.price_pence's default; CHECK (>= 0).
--   template_premium       Premium-gating flag. NOT NULL DEFAULT false.
--   template_image_path    Optional occurrence image path.
--   template_location_reveal_hours / template_booking_cutoff_hours / template_cancellation_window_hours
--                          Optional per-occurrence window overrides in whole hours (NULL = inherit).
--
-- Lifecycle / house columns (mirror events / venues exactly)
--   status           ACTIVE | ENDED | CANCELLED, VARCHAR via EnumType.STRING. NOT NULL DEFAULT 'ACTIVE'.
--                    Distinct from soft-delete: an ENDED/CANCELLED series is still a readable row.
--   created_by       users.id of the creating admin (FK). Resolve the person through UserRepository.
--   created_at/updated_at  created_at is DB-authoritative (DEFAULT now(), read-only on the entity);
--                    updated_at is app-managed.
--   deleted_at       House soft-delete marker (the @SQLRestriction pattern, TM-114): NULL = active,
--                    non-null = tombstoned + hidden from every normal query.
--   version          Optimistic-lock counter (mirrors events.version / venues.version).
CREATE TABLE event_series (
    id                                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    frequency                           VARCHAR(16)  NOT NULL,
    interval_value                      INTEGER      NOT NULL DEFAULT 1 CHECK (interval_value >= 1),
    by_weekday                          INTEGER      CHECK (by_weekday IS NULL OR by_weekday BETWEEN 1 AND 7),
    by_month_day                        INTEGER,
    nth_weekday                         INTEGER,
    rrule_raw                           TEXT,
    timezone                            VARCHAR(64)  NOT NULL,
    first_start_at                      TIMESTAMPTZ  NOT NULL,
    until_date                          DATE,
    occurrence_count                    INTEGER      CHECK (occurrence_count IS NULL OR occurrence_count >= 1),
    horizon_generated_until             TIMESTAMPTZ,
    template_heading                    VARCHAR(255) NOT NULL,
    template_description                VARCHAR(4000) NOT NULL,
    template_location_text              VARCHAR(500) NOT NULL,
    template_city                       VARCHAR(120),
    template_venue_id                   BIGINT       REFERENCES venues (id) ON DELETE SET NULL,
    template_capacity                   INTEGER,
    template_price_pence                INTEGER      NOT NULL DEFAULT 500 CHECK (template_price_pence >= 0),
    template_premium                    BOOLEAN      NOT NULL DEFAULT false,
    template_image_path                 VARCHAR(512),
    template_location_reveal_hours      INTEGER,
    template_booking_cutoff_hours       INTEGER,
    template_cancellation_window_hours  INTEGER,
    status                              VARCHAR(16)  NOT NULL DEFAULT 'ACTIVE',
    created_by                          BIGINT       NOT NULL REFERENCES users (id),
    created_at                          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at                          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at                          TIMESTAMPTZ,
    version                             BIGINT       NOT NULL DEFAULT 0
);

-- The generation scan (TM-790) sweeps ACTIVE series whose horizon needs extending; index status so
-- ENDED/CANCELLED/soft-deleted series never fill the batch.
CREATE INDEX idx_event_series_status ON event_series (status);
