-- V9__create_device_tokens — per-user push device tokens (TM-283 / epic TM-277)
--
-- The durable home for FCM/APNs device tokens so the backend can target pushes to the right
-- devices (TM-284 send-push reads these). One row per registered device token. The token is the
-- natural key for a device: it is globally UNIQUE so a (re)registration upserts cleanly — if the
-- same token is presented again (by the same user, or migrated to a new account on a shared device)
-- the existing row is updated rather than duplicated. Flyway owns this DDL; Hibernate runs
-- validate-only, so the DeviceToken entity must match it exactly.
--
--   user_id     FK to users(id). A user may have many devices; deleting the account cascades the
--               tokens away (a tombstoned/removed account has no devices to push to).
--   token       The opaque FCM registration token. UNIQUE — upsert/dedup key; also what TM-284
--               prunes by value when FCM reports the token `unregistered`.
--   platform    ANDROID | IOS | WEB. Stored as VARCHAR via Hibernate EnumType.STRING (same
--               convention as users.role / users.notification_pref) so values can be added without
--               a DB type change.
--   created_at/updated_at  DB-managed timestamps; updated_at is bumped by the app on re-register.
CREATE TABLE device_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token      VARCHAR(512) NOT NULL UNIQUE,
    platform   VARCHAR(16)  NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Targeting a user's devices on send (TM-284) is a lookup by user_id.
CREATE INDEX idx_device_tokens_user_id ON device_tokens (user_id);
