#!/usr/bin/env bash
# setup-env.sh — bootstrap a working local-dev .env (TM-127).
#
# Why this exists: the committed contract `.env.example` is PRODUCTION-shaped
# (SPRING_PROFILES_ACTIVE=prod, a deliberately BLANK secret DB_PASSWORD). Copying
# it (`cp .env.example .env`) therefore yields a stack that fails to boot locally —
# the compose `${DB_PASSWORD:?}` guard aborts on the empty value. So a fresh clone
# could not `make up` out of the box.
#
# This script writes a `.env` with working *local-dev* defaults so `make up` just
# works from a clean checkout. It is IDEMPOTENT and SAFE:
#   - if `.env` already exists, it is left untouched (never clobbers your real config),
#   - the generated `.env` stays git-ignored (.gitignore blocks `.env` / `.env.*`).
#
# The defaults here are throwaway local values only — never production secrets.
# Production config comes from Secret Manager / Cloud Run, never from this file.
set -euo pipefail

# Resolve the repo root from this script's location so it works from any CWD.
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${REPO_ROOT}/.env"

if [[ -f "${ENV_FILE}" ]]; then
  echo "setup-env: .env already exists — leaving it untouched."
  exit 0
fi

cat > "${ENV_FILE}" <<'EOF'
# Local dev env for docker-compose — generated by `make setup` (scripts/setup-env.sh).
# Throwaway LOCAL defaults only; NEVER commit this file (.gitignore blocks it) and
# never put production secrets here. The production contract lives in .env.example.
#
# Only the vars the compose stack requires. The backend runs the `dev` profile
# (hardcoded in docker-compose.yml) against the in-network Postgres.
DB_NAME=teammarhaba
DB_USER=app
DB_PASSWORD=devpassword
FIREBASE_PROJECT_ID=teammarhaba
EOF

echo "setup-env: wrote ${ENV_FILE} with local-dev defaults."
echo "setup-env: edit it if you need different values; it is git-ignored and safe to keep local."
